import { resolve } from 'node:path'
import { createMarkdownRenderer, disposeMdItInstance } from 'vitepress'
import { describe, expect, it } from 'vitest'
import {
  processSearchTerm,
  splitBookSearchSections,
  splitRenderedPageIntoSections,
  tokenizeSearchText,
} from '../docs/.vitepress/searchIndex'

describe('automatic local search index', () => {
  it('renders a dynamic chapter and splits it by real heading anchors', () => {
    const render = (source: string) => {
      expect(source).toContain('This is a placeholder page')
      expect(source).toContain('构建器会自动发现')
      return [
        '<h1 id="引言">引言 <a href="#引言">#</a></h1>',
        '<p>章节简介。</p>',
        '<h2 id="核心概念">核心概念 <a href="#核心概念">#</a></h2>',
        '<p>中文正文。</p>',
        '<h2 id="core-concepts">Core Concepts <a href="#core-concepts">#</a></h2>',
        '<p>English body.</p>',
      ].join('')
    }
    const sections = splitBookSearchSections(
      resolve('docs/chapters/01-introduction.md'),
      '',
      { render },
    )

    expect(sections).toEqual([
      { anchor: '引言', titles: ['引言'], text: '章节简介。' },
      { anchor: '核心概念', titles: ['引言', '核心概念'], text: '中文正文。' },
      { anchor: 'core-concepts', titles: ['引言', 'Core Concepts'], text: 'English body.' },
    ])
  })

  it('tokenizes Chinese and English search text', () => {
    const tokens = tokenizeSearchText('自动发现 Markdown content')

    expect(tokens).toEqual(expect.arrayContaining(['自动', '发现', 'Markdown', 'content']))
    expect(processSearchTerm('中文')).toEqual(expect.arrayContaining(['中文', '中', '文']))
    expect(processSearchTerm('VitePress')).toBe('vitepress')
  })

  it('keeps heading hierarchy and duplicate anchors from rendered HTML', () => {
    const sections = splitRenderedPageIntoSections([
      '<h1 id="example" tabindex="-1">Example <a class="header-anchor" href="#example">#</a></h1>',
      '<p>Intro text.</p>',
      '<h2 id="details" tabindex="-1">Details <a class="header-anchor" href="#details">#</a></h2>',
      '<p>First details.</p>',
      '<h3 id="nested" tabindex="-1">Nested <a class="header-anchor" href="#nested">#</a></h3>',
      '<p>Nested text.</p>',
      '<h2 id="details-1" tabindex="-1">Details <a class="header-anchor" href="#details-1">#</a></h2>',
      '<p>Second details.</p>',
    ].join(''))

    expect(sections).toEqual([
      { anchor: 'example', titles: ['Example'], text: 'Intro text.' },
      { anchor: 'details', titles: ['Example', 'Details'], text: 'First details.' },
      { anchor: 'nested', titles: ['Example', 'Details', 'Nested'], text: 'Nested text.' },
      { anchor: 'details-1', titles: ['Example', 'Details'], text: 'Second details.' },
    ])
  })

  it('uses the exact anchors generated by VitePress', async () => {
    disposeMdItInstance()
    const markdown = await createMarkdownRenderer(resolve('docs'))
    const html = markdown.render([
      '# Chapter',
      '',
      'Intro.',
      '',
      '## 重复标题',
      '',
      'First section.',
      '',
      '## 重复标题',
      '',
      'Second section.',
    ].join('\n'))

    expect(splitRenderedPageIntoSections(html)).toEqual([
      { anchor: 'chapter', titles: ['Chapter'], text: '\nIntro.\n' },
      { anchor: '重复标题', titles: ['Chapter', '重复标题'], text: '\nFirst section.\n' },
      { anchor: '重复标题-1', titles: ['Chapter', '重复标题'], text: '\nSecond section.\n' },
    ])
    disposeMdItInstance()
  })
})
